language: node_js
node_js:
- 5.2.0
before_install:
- npm install
script:
- webpack
sudo: false
before_deploy:
- npm-prepublish --verbose
deploy:
- provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_KEY"
  on:
    tags: true
env:
  global:
  - secure: Dj5874NFs9uj7RewKRrUswGMUedOf1r8awaNUqHyqjAEroez8Q9akJlbl5z4fUwqu8Hw52Iuz37BcxDZwbr+swz+3Qa2VCYoN8LK+7WzYOxXcKP7nDFbdsnnQJeHSjNISWY4xu4+9knLUSahq0NuiH6f+yGMYY9fFKAxzLp/5wLhbDrIXnnbNiCAAB8WbM623iwSbg+fXnHMoScs5hUNlXGoaZWuL71COlDzfAuUyAQgzQGbKzw4I40T8Eh5ZA4k2kJiN3DqcsTQDEt2UPo+LppL6sFYvkWqcG5ZXHSdP0dQmCUpIBqCeumo8U6o/g+C3ZSRBVTi9f4pXafdPWhV5IU6YCF45+UCe8sOjJwMCSlHqltoYkFJARxKI2guBNMcGniqIGaXqPnoVYaoTON+5Xdkx9PiZt+7mskdR4VSzXXeI3ENQOev2clYQZVTVXvDjIGNEizTC0/JR8T2puHz9BD3R5uz/VxHoNU99pmhLLb3m03HfIOov3Ew1A/9flYLvATPg6iC+LAN9Tal2pA5cSjsqn+i3QWqQOYOHKNk8GQrroT7Kc0ttKxVCYslaBqC5N9AIOC140zgoounDRAiif8S4ZMrL/L2x2XPQjIMn2n8qtsuc8XeVlrTBOCiZIr9sa4cJUgYmUd9YdCrrbksLOV9VsRhmLHGmDq4L7B9c+Y=
  - secure: DmoYFGBQeV7NoLL4jp1KBdyog3Oh4afNO9WMM/5dV3F2QiokgQK/B1NykOYhT4YhsGZyBfwvIkaBOsNoQo+ia1pESx5jtKSPnlirc/iNaaLi0z0QaMfDiaTjIOqyhTZitvFzeyuwWCvLz2ca1ktzWUaKofEFLcvQzs7etO/npA3KhV18ySVaT4oExQtGWrBote4lXBxXIIddPPZpeH9xpmDyZimWfqMGTqKW2iU3dfKLY/ayBJEIsvl9jrzbVaFxPoLSaa5R76ZeVgr7KwPuyprEga+d1OCE4JonRz6Wnfd1Reko13pTAbgqt/Kb1eEYc+ycFJb/kEWkF24/iXS1Jj1J1+3qZkTRm+JI3AnDpHfO+ziwiV+FIvQeK3rxJDoXBGxPrkp2f4+P20Ozn0v4U9liOwPCgBzcnpH6vKqsbqsbHQcOyMyfqeaaMj+7JU0Yc8hJ1qo+xoWj1RE3/wSIGeeDnt2TRwrEAhnZspD079FW8w6NFTQZeyMjwhtg08CVfSK8GOEBAtQ5Yqewn+FH4z2O3NIq3rpaYsEpJClNYia96numaJYnJsO/uXpgTdu0fmIRsqkvaSQzmLoDrqzc/hL/56YXk75CfxwfEVQ//8asgkKARXnY6n2k72nZR6RjVe7dBru8lWPG2nz10PhePJsmsVFSCFdk1iDCRXAXcjc=
